### ISSUE TITLE
ESLint support, better size output

### ISSUE THREAD

**Issue by thibautRe** [sz-piotr/js13k-webpack-starter#1]
Hey, great project!

I forked your repo and made some changes (https://github.com/thibautRe/js13k-2018), I added some features such as user-friendly ZIP bytesize printing, erroring when the size is too big, ESLint + Prettier setup, HTML minification, and I might add more stuff in the next few days.

My question is : are you interested in merging some (or all) of the features in your project? I can send you some pull requests if you want.

Cheers!

**Comment by sz-piotr** [comment]
Go for it. It would surely be helpful :)

**Comment by sz-piotr** [comment]
I merged the changes, but I think it would still be helpful to upgrade to webpack 4. I'll see if I can do that in my free time, or maybe you wish to make some simple adjustments yourself.
